# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-yaml
    -   id: check-added-large-files

# Formatters
-   repo: local
    hooks:
    -   id: fmt
        name: fmt
        entry: cargo fmt
        language: system
        types: [rust]
        args: ["--"]

# Linters
-   repo: local
    hooks:
    -   id: cargo-check
        name: cargo check
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false

-   repo: local
    hooks:
    -   id: clippy
        name: clippy
        entry: cargo clippy
        language: system
        args: ["--", "-D", "warnings"]
        types: [rust]
        pass_filenames: false
